import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import ScrollToTop from './../components/scriollTop';
import WhatsAppButton from './../components/whatsapp';
import RouteProgressBar from './../components/RouteProgressBar';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MostaSoft",
  description: "Generated by create next app",
   verification: {
    google: "OgeIILS0kyTPxcsi3Y3eXpS3rKZpV2z8E5XBlDWBpzA",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <NavBar/>
         <RouteProgressBar/>
        {children}
        <ScrollToTop/>
        <WhatsAppButton/>
         <Footer/>
      </body>
    </html>
  );
}
