import type { Metadata } from "next";
import { Rajdhani } from "next/font/google";
import "./globals.css";
import ResponsiveNav from "@/components/Home/NavBar/ResponsiveNav";
import Provider from "@/components/HOC/provider";

const font = Rajdhani({
  weight:["300", "400", "500", "600", "700"],
  subsets: ["latin"]
})





export const metadata: Metadata = {
  title: "MostaSoft Industry ltd",
  description: "Generated by MostaSoft Industry ltd ",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={` ${font.className} antialiased`} >
       <Provider>
        <ResponsiveNav/>
        {children}
        </Provider>
      </body>
    </html>
  );
}
